name: Create tag and release before promotion ot QA

on:
  issue_comment:
    types: [created]

jobs:
  promote-to-qa:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/tag qa')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR base and head
        id: pr_info
        run: |
          BASE_BRANCH=$(jq -r .pull_request.base.ref < $GITHUB_EVENT_PATH)
          HEAD_BRANCH=$(jq -r .pull_request.head.ref < $GITHUB_EVENT_PATH)
          echo "base=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "head=$HEAD_BRANCH" >> $GITHUB_OUTPUT

      # ✅ Step 1: Get the latest release tag
      - name: Get latest release tag
        id: prev_release
        run: |
          PREV_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Step 2: Generate a new tag version
      - name: Create new tag
        id: new_tag
        run: |
          DATE_TAG="v$(date +'%Y.%m.%d').${{ github.run_number }}"
          echo "new_tag=$DATE_TAG" >> $GITHUB_OUTPUT
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $DATE_TAG
          git push origin $DATE_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Step 3: Generate PR summary
      - name: Generate PR summary section
        run: |
          echo "## Merged Pull Requests" > CHANGELOG.md
          echo "" >> CHANGELOG.md

          gh pr list \
            --state merged \
            --base ${{ steps.pr_info.outputs.base }} \
            --json number,title,author \
            --jq '.[] | "- PR #\(.number): \(.title) by @\(.author.login)"' \
            >> CHANGELOG.md

          echo "" >> CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Step 4: Generate full changelog (commits since last release)
      - name: Generate full changelog (commit log)
        run: |
          echo "## Full Changelog" >> CHANGELOG.md
          echo "" >> CHANGELOG.md

          BASE=${{ steps.prev_release.outputs.prev_tag }}
          NEW=${{ steps.new_tag.outputs.new_tag }}

          git fetch origin $BASE $NEW
          git log $BASE..$NEW --pretty=format:"* %s (%h) by %an" >> CHANGELOG.md

          echo "" >> CHANGELOG.md
          echo "Final CHANGELOG.md:"
          cat CHANGELOG.md

      # ✅ Step 5: Create a new release for the new tag
      - name: Create GitHub Release
        run: |
          gh release create ${{ steps.new_tag.outputs.new_tag }} \
            --title "Release ${{ steps.new_tag.outputs.new_tag }}" \
            --notes-file CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Step 6: Deploy to QA
      - name: Deploy to QA
        run: |
          echo "Deploying release ${{ steps.new_tag.outputs.new_tag }} to QA..."
          # your deployment commands here
